/*
  Auto generated by version 0.0 of material_constant_generator.py
  on geop-318.ethz.ch, at 2015-09-22 11:27:29.366215 by dmay
*/

#ifndef __EnergyConductivityConst_DEF_H__
#define __EnergyConductivityConst_DEF_H__

typedef struct {
 double k0;
} EnergyConductivityConst;

typedef enum {
  ConductivityConst_k0 = 0
} EnergyConductivityConstTypeName;

extern const char EnergyConductivityConst_classname[];

extern const int EnergyConductivityConst_nmembers;

extern const size_t EnergyConductivityConst_member_sizes[];

extern const char *EnergyConductivityConst_member_names[];

/* prototypes */
void EnergyConductivityConstGetField_k0(EnergyConductivityConst *point,double *data);
void EnergyConductivityConstSetField_k0(EnergyConductivityConst *point,double data);
void EnergyConductivityConstView(EnergyConductivityConst *point);

void EnergyConductivityConstGetDefault_k0(double *data);
void MaterialConstantsSetDefaultAll_ConductivityConst(int nr,EnergyConductivityConst _data[]);
PetscErrorCode MaterialConstantsSetFromOptions_ConductivityConst(const char model_name[],const int region_id,EnergyConductivityConst _data[],PetscBool essential);
PetscErrorCode MaterialConstantsPrintValues_ConductivityConst(const char model_name[],const int region_id,EnergyConductivityConst _data[]);
PetscErrorCode MaterialConstantsSetValues_ConductivityConst(const int region_id,EnergyConductivityConst _data[],double k0);
PetscErrorCode MaterialConstantsScaleValues_ConductivityConst(const int region_id,EnergyConductivityConst _data[],double k0);


#endif
