/*
  Auto generated by version 0.0 of material_constant_generator.py
  on eduroam-nw-dock-1-133.ethz.ch, at 2015-09-21 13:23:20.590019 by gduclaux
*/

#ifndef __EnergySourceAdiabaticAdvection_DEF_H__
#define __EnergySourceAdiabaticAdvection_DEF_H__

typedef struct {
 double dTdy;
} EnergySourceAdiabaticAdvection;

typedef enum {
  SourceAdiabaticAdv_VerticalThermalGradient = 0
} EnergySourceAdiabaticAdvectionTypeName;

extern const char EnergySourceAdiabaticAdvection_classname[];

extern const int EnergySourceAdiabaticAdvection_nmembers;

extern const size_t EnergySourceAdiabaticAdvection_member_sizes[];

extern const char *EnergySourceAdiabaticAdvection_member_names[];

/* prototypes */
void EnergySourceAdiabaticAdvectionGetField_VerticalThermalGradient(EnergySourceAdiabaticAdvection *point,double *data);
void EnergySourceAdiabaticAdvectionSetField_VerticalThermalGradient(EnergySourceAdiabaticAdvection *point,double data);
void EnergySourceAdiabaticAdvectionView(EnergySourceAdiabaticAdvection *point);

void EnergySourceAdiabaticAdvectionGetDefault_VerticalThermalGradient(double *data);
void MaterialConstantsSetDefaultAll_SourceAdiabaticAdv(int nr,EnergySourceAdiabaticAdvection _data[]);
PetscErrorCode MaterialConstantsSetFromOptions_SourceAdiabaticAdv(const char model_name[],const int region_id,EnergySourceAdiabaticAdvection _data[],PetscBool essential);
PetscErrorCode MaterialConstantsPrintValues_SourceAdiabaticAdv(const char model_name[],const int region_id,EnergySourceAdiabaticAdvection _data[]);
PetscErrorCode MaterialConstantsSetValues_SourceAdiabaticAdv(const int region_id,EnergySourceAdiabaticAdvection _data[],double dTdy);
PetscErrorCode MaterialConstantsScaleValues_SourceAdiabaticAdv(const int region_id,EnergySourceAdiabaticAdvection _data[],double dTdy);


#endif
