/*@ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 **
 **    Copyright (c) 2012
 **        Dave A. May [dave.may@erdw.ethz.ch]
 **        Institute of Geophysics
 **        ETH Zürich
 **        Sonneggstrasse 5
 **        CH-8092 Zürich
 **        Switzerland
 **
 **    project:    pTatin3d
 **    filename:   MaterialConst_ViscosityConst_def.h
 **
 **
 **    pTatin3d is free software: you can redistribute it and/or modify
 **    it under the terms of the GNU General Public License as published
 **    by the Free Software Foundation, either version 3 of the License,
 **    or (at your option) any later version.
 **
 **    pTatin3d is distributed in the hope that it will be useful,
 **    but WITHOUT ANY WARRANTY; without even the implied warranty of
 **    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 **    See the GNU General Public License for more details.
 **
 **    You should have received a copy of the GNU General Public License
 **    along with pTatin3d. If not, see <http://www.gnu.org/licenses/>.
 **
 ** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ @*/
/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on les-MacBook-Pro.local, at 2013-03-08 17:43:59.343400 by laetitia
*/


#ifndef __MaterialConst_ViscosityConst_DEF_H__
#define __MaterialConst_ViscosityConst_DEF_H__

typedef struct {
  double eta0 ;
} MaterialConst_ViscosityConst ;


typedef enum {
  ViscConst_eta0 = 0
} MaterialConst_ViscosityConstTypeName ;


extern const char MaterialConst_ViscosityConst_classname[];

extern const int MaterialConst_ViscosityConst_nmembers;

extern const size_t MaterialConst_ViscosityConst_member_sizes[];

extern const char *MaterialConst_ViscosityConst_member_names[];

/* prototypes */
void MaterialConst_ViscosityConstGetField_eta0(MaterialConst_ViscosityConst *point,double *data);
void MaterialConst_ViscosityConstSetField_eta0(MaterialConst_ViscosityConst *point,double data);
void MaterialConst_ViscosityConstView(MaterialConst_ViscosityConst *point);
void MaterialConst_ViscosityConstVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_ViscosityConst points[]);
void MaterialConst_ViscosityConstPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_ViscosityConstVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_ViscosityConst points[]);
void MaterialConst_ViscosityConstVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_ViscosityConst points[]);

#endif
