/*
  Auto generated by version 0.0 of material_constant_generator.py
  on eduroam-nw-dock-1-133.ethz.ch, at 2015-09-21 13:23:20.590158 by gduclaux
*/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <petsc.h>

#include "EnergySourceAdiabaticAdvection_def.h"


PetscErrorCode MaterialConstantsReportParseError(const char model_name[],const char field_name[],const int region);

const char EnergySourceAdiabaticAdvection_classname[] = "EnergySourceAdiabaticAdvection";

const int EnergySourceAdiabaticAdvection_nmembers = 1;

const size_t EnergySourceAdiabaticAdvection_member_sizes[] = {
  1 * sizeof(double)
};

const char *EnergySourceAdiabaticAdvection_member_names[] = {
  "VerticalThermalGradient"
};


/* ================================================================= */
/*   Getters for EnergySourceAdiabaticAdvection */
/* ================================================================= */
void EnergySourceAdiabaticAdvectionGetField_VerticalThermalGradient(EnergySourceAdiabaticAdvection *point,double *data) 
{
  *data = point->dTdy;
}


/* ================================================================= */
/*   Setters for EnergySourceAdiabaticAdvection */
/* ================================================================= */
void EnergySourceAdiabaticAdvectionSetField_VerticalThermalGradient(EnergySourceAdiabaticAdvection *point,double data) 
{
  point->dTdy = data;
}


/* ================================================================= */
/*   C-viewer for EnergySourceAdiabaticAdvection */
/* ================================================================= */
void EnergySourceAdiabaticAdvectionView(EnergySourceAdiabaticAdvection *point)
{
  {
    double data;
    EnergySourceAdiabaticAdvectionGetField_VerticalThermalGradient(point,&data);
    printf("field: VerticalThermalGradient = %1.6e; [size %zu; type double; variable_name dTdy]\n",data, EnergySourceAdiabaticAdvection_member_sizes[0] );
  }
}


/* ================================================================= */
/*   Getters for default parameters (EnergySourceAdiabaticAdvection) */
/* ================================================================= */
void EnergySourceAdiabaticAdvectionGetDefault_VerticalThermalGradient(double *data) 
{
  *data = (double)0.0;
}

void MaterialConstantsSetDefaultAll_SourceAdiabaticAdv( 
    int nr,EnergySourceAdiabaticAdvection _data[])
{
  int r; 

  for (r=0; r<nr; r++) {
    { double value;
      EnergySourceAdiabaticAdvectionGetDefault_VerticalThermalGradient((double*)&value);
      EnergySourceAdiabaticAdvectionSetField_VerticalThermalGradient(&_data[r],(double)value);
    }

  }

} 

#undef __FUNCT__
#define __FUNCT__ "MaterialConstantsSetFromOptions_SourceAdiabaticAdv"
PetscErrorCode MaterialConstantsSetFromOptions_SourceAdiabaticAdv(const char model_name[],const int region_id,EnergySourceAdiabaticAdvection _data[],PetscBool essential)
{
  char                         opt_name[PETSC_MAX_PATH_LEN];
  PetscBool                    found;
  PetscErrorCode               ierr;

  EnergySourceAdiabaticAdvection *data = &_data[region_id];
  /* options for VerticalThermalGradient ==>> dTdy */
  sprintf(opt_name,"-VerticalThermalGradient_%d",region_id);
  { PetscReal value;
    ierr = PetscOptionsGetReal(NULL,model_name,opt_name,&value,&found);CHKERRQ(ierr);
    if (found) { EnergySourceAdiabaticAdvectionSetField_VerticalThermalGradient(data,(double)value); }
    else if ( (!found)  && (essential) ) {
      ierr = MaterialConstantsReportParseError(model_name,"VerticalThermalGradient",region_id);CHKERRQ(ierr);
  }}

  PetscFunctionReturn(0);
} 

#undef __FUNCT__
#define __FUNCT__ "MaterialConstantsPrintValues_SourceAdiabaticAdv"
PetscErrorCode MaterialConstantsPrintValues_SourceAdiabaticAdv(const char model_name[],const int region_id,EnergySourceAdiabaticAdvection _data[]) 
{
  EnergySourceAdiabaticAdvection *data = &_data[region_id];
  char   opt_name[PETSC_MAX_PATH_LEN];

  PetscPrintf(PETSC_COMM_WORLD,"------------------------------------------------------------------------------------------------\n");
  PetscPrintf(PETSC_COMM_WORLD,"  MaterialView(SourceAdiabaticAdv): RegionIndex[%d]\n", region_id);
  /* options for VerticalThermalGradient ==>> dTdy */
  sprintf(opt_name,"-%s_VerticalThermalGradient_%d", model_name,region_id);
  { double value;
    EnergySourceAdiabaticAdvectionGetField_VerticalThermalGradient(data,(double*)&value);
    PetscPrintf(PETSC_COMM_WORLD,"    VerticalThermalGradient = %1.4e (%s) \n", value,opt_name); 
  }

  PetscFunctionReturn(0);
} 

#undef __FUNCT__
#define __FUNCT__ "MaterialConstantsSetValues_SourceAdiabaticAdv"
PetscErrorCode MaterialConstantsSetValues_SourceAdiabaticAdv(const int region_id,EnergySourceAdiabaticAdvection _data[],
    double dTdy)
{
  EnergySourceAdiabaticAdvection *data = &_data[region_id];
  data->dTdy =  dTdy;
  PetscFunctionReturn(0);
} 

#undef __FUNCT__
#define __FUNCT__ "MaterialConstantsScaleValues_SourceAdiabaticAdv"
PetscErrorCode MaterialConstantsScaleValues_SourceAdiabaticAdv(const int region_id,EnergySourceAdiabaticAdvection _data[],
    double dTdy)
{
  EnergySourceAdiabaticAdvection *data = &_data[region_id];

  { double value;
    EnergySourceAdiabaticAdvectionGetField_VerticalThermalGradient(data,(double*)&value);
    value = value / dTdy;
    EnergySourceAdiabaticAdvectionSetField_VerticalThermalGradient(data,(double)value);
  }

  PetscFunctionReturn(0);
} 

