/*
  Auto generated by version 0.0 of material_constant_generator.py
  on eduroam-nw-dock-1-133.ethz.ch, at 2015-09-21 13:23:20.589192 by gduclaux
*/

#ifndef __EnergySourceConst_DEF_H__
#define __EnergySourceConst_DEF_H__

typedef struct {
 double H;
} EnergySourceConst;

typedef enum {
  SourceConst_HeatSource = 0
} EnergySourceConstTypeName;

extern const char EnergySourceConst_classname[];

extern const int EnergySourceConst_nmembers;

extern const size_t EnergySourceConst_member_sizes[];

extern const char *EnergySourceConst_member_names[];

/* prototypes */
void EnergySourceConstGetField_HeatSource(EnergySourceConst *point,double *data);
void EnergySourceConstSetField_HeatSource(EnergySourceConst *point,double data);
void EnergySourceConstView(EnergySourceConst *point);

void EnergySourceConstGetDefault_HeatSource(double *data);
void MaterialConstantsSetDefaultAll_SourceConst(int nr,EnergySourceConst _data[]);
PetscErrorCode MaterialConstantsSetFromOptions_SourceConst(const char model_name[],const int region_id,EnergySourceConst _data[],PetscBool essential);
PetscErrorCode MaterialConstantsPrintValues_SourceConst(const char model_name[],const int region_id,EnergySourceConst _data[]);
PetscErrorCode MaterialConstantsSetValues_SourceConst(const int region_id,EnergySourceConst _data[],double H);
PetscErrorCode MaterialConstantsScaleValues_SourceConst(const int region_id,EnergySourceConst _data[],double H);


#endif
