/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on otsu.local, at 2013-01-28 10:38:57.346580 by dmay
*/


#ifndef __MaterialConst_ViscosityConst_DEF_H__
#define __MaterialConst_ViscosityConst_DEF_H__

typedef struct {
  double eta0 ;
} MaterialConst_ViscosityConst ;


typedef enum {
  ViscConst_eta0 = 0
} MaterialConst_ViscosityConstTypeName ;


extern const char MaterialConst_ViscosityConst_classname[];

extern const int MaterialConst_ViscosityConst_nmembers;

extern const size_t MaterialConst_ViscosityConst_member_sizes[];

extern const char *MaterialConst_ViscosityConst_member_names[];

/* prototypes */
void MaterialConst_ViscosityConstGetField_eta0(MaterialConst_ViscosityConst *point,double *data);
void MaterialConst_ViscosityConstSetField_eta0(MaterialConst_ViscosityConst *point,double data);
void MaterialConst_ViscosityConstView(MaterialConst_ViscosityConst *point);
void MaterialConst_ViscosityConstVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_ViscosityConst points[]);
void MaterialConst_ViscosityConstPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_ViscosityConstVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_ViscosityConst points[]);
void MaterialConst_ViscosityConstVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_ViscosityConst points[]);

#endif
