/*@ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 **
 **    Copyright (c) 2012, 
 **        Dave A. May [dave.may@erdw.ethz.ch]
 **        Geophysical Fluid Dynamics, 
 **        Department of Earth Sciences,
 **        ETH Zürich,
 **        Sonneggstrasse 5,
 **        CH-8092 Zurich,
 **        Switzerland
 **
 **    Project:       pTatin3d
 **    Filename:      MaterialConst_DensityConst_def.h
 **
 **
 **    pTatin3d is free software: you can redistribute it and/or modify
 **    it under the terms of the GNU General Public License as published by
 **    the Free Software Foundation, either version 3 of the License, or
 **    (at your option) any later version.
 **
 **    pTatin3d is distributed in the hope that it will be useful,
 **    but WITHOUT ANY WARRANTY; without even the implied warranty of
 **    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 **    GNU General Public License for more details.
 **
 **    You should have received a copy of the GNU General Public License
 **    along with pTatin3d.  If not, see <http://www.gnu.org/licenses/>.
 **
 **
 **    $Id$
 **
 ** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~@*/
/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on vpn-global-234-dhcp.ethz.ch, at 2013-01-29 13:09:58.418214 by laetitia
*/


#ifndef __MaterialConst_DensityConst_DEF_H__
#define __MaterialConst_DensityConst_DEF_H__

typedef struct {
  double density ;
} MaterialConst_DensityConst ;


typedef enum {
  DensityConst_density = 0
} MaterialConst_DensityConstTypeName ;


extern const char MaterialConst_DensityConst_classname[];

extern const int MaterialConst_DensityConst_nmembers;

extern const size_t MaterialConst_DensityConst_member_sizes[];

extern const char *MaterialConst_DensityConst_member_names[];

/* prototypes */
void MaterialConst_DensityConstGetField_density(MaterialConst_DensityConst *point,double *data);
void MaterialConst_DensityConstSetField_density(MaterialConst_DensityConst *point,double data);
void MaterialConst_DensityConstView(MaterialConst_DensityConst *point);
void MaterialConst_DensityConstVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityConst points[]);
void MaterialConst_DensityConstPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_DensityConstVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_DensityConst points[]);
void MaterialConst_DensityConstVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityConst points[]);

#endif
