/*
  Auto generated by version 0.0 of mat_prop_class_generator.py
  on otsu.local, at 2012-08-27 10:57:20.384973 by dmay
*/


#ifndef __MaterialConst_PlasticMises_DEF_H__
#define __MaterialConst_PlasticMises_DEF_H__

typedef struct {
  double tau_yield ;
  double tau_yield_inf ;
} MaterialConst_PlasticMises ;


typedef enum {
  PlasticMises_yield_stress = 0,
  PlasticMises_yield_stress_inf
} MaterialConst_PlasticMisesTypeName ;


extern const char MaterialConst_PlasticMises_classname[];

extern const char MaterialConst_PlasticMises_classname_short[];

extern const int MaterialConst_PlasticMises_nmembers;

extern const size_t MaterialConst_PlasticMises_member_sizes[];

extern const char *MaterialConst_PlasticMises_member_names_short[];

extern const char *MaterialConst_PlasticMises_member_names[];

extern const size_t MaterialConst_PlasticMises_member_byte_offset[];

/* prototypes */
void MaterialConst_PlasticMisesGetField_yield_stress(MaterialConst_PlasticMises *point,double *data);
void MaterialConst_PlasticMisesGetField_yield_stress_inf(MaterialConst_PlasticMises *point,double *data);
void MaterialConst_PlasticMisesSetField_yield_stress(MaterialConst_PlasticMises *point,double data);
void MaterialConst_PlasticMisesSetField_yield_stress_inf(MaterialConst_PlasticMises *point,double data);
void MaterialConst_PlasticMisesView(MaterialConst_PlasticMises *point);

#endif
