
/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on les-MacBook-Pro.local, at 2013-01-28 12:41:37.374516 by laetitia
*/


#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "MaterialConst_PlasticDP_def.h"


const char MaterialConst_PlasticDP_classname[] = "MaterialConst_PlasticDP";

const int MaterialConst_PlasticDP_nmembers = 4;

const size_t MaterialConst_PlasticDP_member_sizes[] = {
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double)
} ;

const char *MaterialConst_PlasticDP_member_names[] = {
  "friction",
  "cohesion",
  "friction_inf",
  "cohesion_inf"
} ;


/* ===================================== */
/* Getters for MaterialConst_PlasticDP */
/* ===================================== */
void MaterialConst_PlasticDPGetField_friction(MaterialConst_PlasticDP *point,double *data) 
{
  *data = point->phi;
}

void MaterialConst_PlasticDPGetField_cohesion(MaterialConst_PlasticDP *point,double *data) 
{
  *data = point->Co;
}

void MaterialConst_PlasticDPGetField_friction_inf(MaterialConst_PlasticDP *point,double *data) 
{
  *data = point->phi_inf;
}

void MaterialConst_PlasticDPGetField_cohesion_inf(MaterialConst_PlasticDP *point,double *data) 
{
  *data = point->Co_inf;
}


/* ===================================== */
/* Setters for MaterialConst_PlasticDP */
/* ===================================== */
void MaterialConst_PlasticDPSetField_friction(MaterialConst_PlasticDP *point,double data) 
{
  point->phi = data;
}

void MaterialConst_PlasticDPSetField_cohesion(MaterialConst_PlasticDP *point,double data) 
{
  point->Co = data;
}

void MaterialConst_PlasticDPSetField_friction_inf(MaterialConst_PlasticDP *point,double data) 
{
  point->phi_inf = data;
}

void MaterialConst_PlasticDPSetField_cohesion_inf(MaterialConst_PlasticDP *point,double data) 
{
  point->Co_inf = data;
}


/* ===================================== */
/* C-viewer for MaterialConst_PlasticDP */
/* ===================================== */
void MaterialConst_PlasticDPView(MaterialConst_PlasticDP *point)
{
  {
    double data;
    MaterialConst_PlasticDPGetField_friction(point,&data);
    printf("field: friction = %1.6e; [size %zu; type double; variable_name phi]\n",data, MaterialConst_PlasticDP_member_sizes[0] );
  }
  {
    double data;
    MaterialConst_PlasticDPGetField_cohesion(point,&data);
    printf("field: cohesion = %1.6e; [size %zu; type double; variable_name Co]\n",data, MaterialConst_PlasticDP_member_sizes[1] );
  }
  {
    double data;
    MaterialConst_PlasticDPGetField_friction_inf(point,&data);
    printf("field: friction_inf = %1.6e; [size %zu; type double; variable_name phi_inf]\n",data, MaterialConst_PlasticDP_member_sizes[2] );
  }
  {
    double data;
    MaterialConst_PlasticDPGetField_cohesion_inf(point,&data);
    printf("field: cohesion_inf = %1.6e; [size %zu; type double; variable_name Co_inf]\n",data, MaterialConst_PlasticDP_member_sizes[3] );
  }
}


/* ===================================== */
/* VTK viewer for MaterialConst_PlasticDP */
/* ===================================== */
void MaterialConst_PlasticDPVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_PlasticDP points[]) 
{
  int p;
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"phi\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].phi);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Co\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].Co);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"phi_inf\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].phi_inf);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Co_inf\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].Co_inf);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
}


/* ===================================== */
/* PVTU viewer for MaterialConst_PlasticDP */
/* ===================================== */
void MaterialConst_PlasticDPPVTUWriteAllPPointDataFields(FILE *vtk_fp) 
{
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"phi\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"Co\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"phi_inf\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"Co_inf\" NumberOfComponents=\"1\"/>\n");
}


/* ===================================== */
/* VTK binary (appended header) viewer for MaterialConst_PlasticDP */
/* ===================================== */
void MaterialConst_PlasticDPVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_PlasticDP points[]) 
{
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"phi\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Co\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"phi_inf\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Co_inf\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

}


/* ================================================== */
/* VTK binary (appended data) viewer for MaterialConst_PlasticDP */
/* ==================================================== */
void MaterialConst_PlasticDPVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_PlasticDP points[]) 
{
  int p,length;
  size_t atomic_size;

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].phi,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].Co,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].phi_inf,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].Co_inf,atomic_size,1,vtk_fp);
  }

}

