/*@ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 **
 **    Copyright (c) 2012
 **        Dave A. May [dave.may@erdw.ethz.ch]
 **        Institute of Geophysics
 **        ETH Zürich
 **        Sonneggstrasse 5
 **        CH-8092 Zürich
 **        Switzerland
 **
 **    project:    pTatin3d
 **    filename:   MaterialConst_ViscosityFK_def.h
 **
 **
 **    pTatin3d is free software: you can redistribute it and/or modify
 **    it under the terms of the GNU General Public License as published
 **    by the Free Software Foundation, either version 3 of the License,
 **    or (at your option) any later version.
 **
 **    pTatin3d is distributed in the hope that it will be useful,
 **    but WITHOUT ANY WARRANTY; without even the implied warranty of
 **    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 **    See the GNU General Public License for more details.
 **
 **    You should have received a copy of the GNU General Public License
 **    along with pTatin3d. If not, see <http://www.gnu.org/licenses/>.
 **
 ** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ @*/
/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on les-MacBook-Pro.local, at 2013-03-08 17:43:59.344551 by laetitia
*/


#ifndef __MaterialConst_ViscosityFK_DEF_H__
#define __MaterialConst_ViscosityFK_DEF_H__

typedef struct {
  double eta0 ;
  double theta ;
} MaterialConst_ViscosityFK ;


typedef enum {
  ViscosityFK_eta0 = 0,
  ViscosityFK_theta
} MaterialConst_ViscosityFKTypeName ;


extern const char MaterialConst_ViscosityFK_classname[];

extern const int MaterialConst_ViscosityFK_nmembers;

extern const size_t MaterialConst_ViscosityFK_member_sizes[];

extern const char *MaterialConst_ViscosityFK_member_names[];

/* prototypes */
void MaterialConst_ViscosityFKGetField_eta0(MaterialConst_ViscosityFK *point,double *data);
void MaterialConst_ViscosityFKGetField_theta(MaterialConst_ViscosityFK *point,double *data);
void MaterialConst_ViscosityFKSetField_eta0(MaterialConst_ViscosityFK *point,double data);
void MaterialConst_ViscosityFKSetField_theta(MaterialConst_ViscosityFK *point,double data);
void MaterialConst_ViscosityFKView(MaterialConst_ViscosityFK *point);
void MaterialConst_ViscosityFKVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_ViscosityFK points[]);
void MaterialConst_ViscosityFKPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_ViscosityFKVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_ViscosityFK points[]);
void MaterialConst_ViscosityFKVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_ViscosityFK points[]);

#endif
