/*@ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 **
 **    Copyright (c) 2012, 
 **        Dave A. May [dave.may@erdw.ethz.ch]
 **        Geophysical Fluid Dynamics, 
 **        Department of Earth Sciences,
 **        ETH Zürich,
 **        Sonneggstrasse 5,
 **        CH-8092 Zurich,
 **        Switzerland
 **
 **    Project:       pTatin3d
 **    Filename:      MaterialConst_PlasticMises_def.c
 **
 **
 **    pTatin3d is free software: you can redistribute it and/or modify
 **    it under the terms of the GNU General Public License as published by
 **    the Free Software Foundation, either version 3 of the License, or
 **    (at your option) any later version.
 **
 **    pTatin3d is distributed in the hope that it will be useful,
 **    but WITHOUT ANY WARRANTY; without even the implied warranty of
 **    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 **    GNU General Public License for more details.
 **
 **    You should have received a copy of the GNU General Public License
 **    along with pTatin3d.  If not, see <http://www.gnu.org/licenses/>.
 **
 **
 **    $Id$
 **
 ** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~@*/
/*
  Auto generated by version 0.0 of mat_prop_class_generator.py
  on otsu.local, at 2012-08-27 10:57:20.385188 by dmay
*/


#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "MaterialConst_PlasticMises_def.h"


const char MaterialConst_PlasticMises_classname[] = "MaterialConst_PlasticMises";

const char MaterialConst_PlasticMises_classname_short[] = "PlasticMises";

const int MaterialConst_PlasticMises_nmembers = 2;

const size_t MaterialConst_PlasticMises_member_sizes[] = {
  1 * sizeof(double),
  1 * sizeof(double)
} ;

const size_t MaterialConst_PlasticMises_member_byte_offset[] = {
  0,
  0 + 1*sizeof(double)
} ;

const char *MaterialConst_PlasticMises_member_names_short[] = {
  "tau_yield",
  "tau_yield_inf"
} ;

const char *MaterialConst_PlasticMises_member_names[] = {
  "yield_stress",
  "yield_stress_inf"
} ;


/* ===================================== */
/* Getters for MaterialConst_PlasticMises */
/* ===================================== */
void MaterialConst_PlasticMisesGetField_yield_stress(MaterialConst_PlasticMises *point,double *data) 
{
  *data = point->tau_yield;
}

void MaterialConst_PlasticMisesGetField_yield_stress_inf(MaterialConst_PlasticMises *point,double *data) 
{
  *data = point->tau_yield_inf;
}


/* ===================================== */
/* Setters for MaterialConst_PlasticMises */
/* ===================================== */
void MaterialConst_PlasticMisesSetField_yield_stress(MaterialConst_PlasticMises *point,double data) 
{
  point->tau_yield = data;
}

void MaterialConst_PlasticMisesSetField_yield_stress_inf(MaterialConst_PlasticMises *point,double data) 
{
  point->tau_yield_inf = data;
}


/* ===================================== */
/* C-viewer for MaterialConst_PlasticMises */
/* ===================================== */
void MaterialConst_PlasticMisesView(MaterialConst_PlasticMises *point)
{
  {
    double data;
    MaterialConst_PlasticMisesGetField_yield_stress(point,&data);
    printf("field: yield_stress = %1.6e; [size %zu; type double; variable_name tau_yield]\n",data, MaterialConst_PlasticMises_member_sizes[0] );
  }
  {
    double data;
    MaterialConst_PlasticMisesGetField_yield_stress_inf(point,&data);
    printf("field: yield_stress_inf = %1.6e; [size %zu; type double; variable_name tau_yield_inf]\n",data, MaterialConst_PlasticMises_member_sizes[1] );
  }
}

