/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on les-MacBook-Pro.local, at 2013-03-08 17:43:59.346854 by laetitia
*/


#ifndef __MaterialConst_SoftLin_DEF_H__
#define __MaterialConst_SoftLin_DEF_H__

typedef struct {
  double eps_min ;
  double eps_max ;
} MaterialConst_SoftLin ;


typedef enum {
  SoftLin_eps_min = 0,
  SoftLin_eps_max
} MaterialConst_SoftLinTypeName ;


extern const char MaterialConst_SoftLin_classname[];

extern const int MaterialConst_SoftLin_nmembers;

extern const size_t MaterialConst_SoftLin_member_sizes[];

extern const char *MaterialConst_SoftLin_member_names[];

/* prototypes */
void MaterialConst_SoftLinGetField_eps_min(MaterialConst_SoftLin *point,double *data);
void MaterialConst_SoftLinGetField_eps_max(MaterialConst_SoftLin *point,double *data);
void MaterialConst_SoftLinSetField_eps_min(MaterialConst_SoftLin *point,double data);
void MaterialConst_SoftLinSetField_eps_max(MaterialConst_SoftLin *point,double data);
void MaterialConst_SoftLinView(MaterialConst_SoftLin *point);
void MaterialConst_SoftLinVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_SoftLin points[]);
void MaterialConst_SoftLinPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_SoftLinVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_SoftLin points[]);
void MaterialConst_SoftLinVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_SoftLin points[]);

#endif
