/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on vpn-global-234-dhcp.ethz.ch, at 2013-01-29 13:09:58.418214 by laetitia
*/


#ifndef __MaterialConst_DensityConst_DEF_H__
#define __MaterialConst_DensityConst_DEF_H__

typedef struct {
  double density ;
} MaterialConst_DensityConst ;


typedef enum {
  DensityConst_density = 0
} MaterialConst_DensityConstTypeName ;


extern const char MaterialConst_DensityConst_classname[];

extern const int MaterialConst_DensityConst_nmembers;

extern const size_t MaterialConst_DensityConst_member_sizes[];

extern const char *MaterialConst_DensityConst_member_names[];

/* prototypes */
void MaterialConst_DensityConstGetField_density(MaterialConst_DensityConst *point,double *data);
void MaterialConst_DensityConstSetField_density(MaterialConst_DensityConst *point,double data);
void MaterialConst_DensityConstView(MaterialConst_DensityConst *point);
void MaterialConst_DensityConstVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityConst points[]);
void MaterialConst_DensityConstPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_DensityConstVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_DensityConst points[]);
void MaterialConst_DensityConstVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityConst points[]);

#endif
