/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on vpn-global-234-dhcp.ethz.ch, at 2013-01-29 13:09:58.418366 by laetitia
*/


#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "MaterialConst_DensityConst_def.h"


const char MaterialConst_DensityConst_classname[] = "MaterialConst_DensityConst";

const int MaterialConst_DensityConst_nmembers = 1;

const size_t MaterialConst_DensityConst_member_sizes[] = {
  1 * sizeof(double)
} ;

const char *MaterialConst_DensityConst_member_names[] = {
  "density"
} ;


/* ===================================== */
/* Getters for MaterialConst_DensityConst */
/* ===================================== */
void MaterialConst_DensityConstGetField_density(MaterialConst_DensityConst *point,double *data) 
{
  *data = point->density;
}


/* ===================================== */
/* Setters for MaterialConst_DensityConst */
/* ===================================== */
void MaterialConst_DensityConstSetField_density(MaterialConst_DensityConst *point,double data) 
{
  point->density = data;
}


/* ===================================== */
/* C-viewer for MaterialConst_DensityConst */
/* ===================================== */
void MaterialConst_DensityConstView(MaterialConst_DensityConst *point)
{
  {
    double data;
    MaterialConst_DensityConstGetField_density(point,&data);
    printf("field: density = %1.6e; [size %zu; type double; variable_name density]\n",data, MaterialConst_DensityConst_member_sizes[0] );
  }
}


/* ===================================== */
/* VTK viewer for MaterialConst_DensityConst */
/* ===================================== */
void MaterialConst_DensityConstVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityConst points[]) 
{
  int p;
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"density\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].density);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
}


/* ===================================== */
/* PVTU viewer for MaterialConst_DensityConst */
/* ===================================== */
void MaterialConst_DensityConstPVTUWriteAllPPointDataFields(FILE *vtk_fp) 
{
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"density\" NumberOfComponents=\"1\"/>\n");
}


/* ===================================== */
/* VTK binary (appended header) viewer for MaterialConst_DensityConst */
/* ===================================== */
void MaterialConst_DensityConstVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_DensityConst points[]) 
{
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"density\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

}


/* ================================================== */
/* VTK binary (appended data) viewer for MaterialConst_DensityConst */
/* ==================================================== */
void MaterialConst_DensityConstVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityConst points[]) 
{
  int p,length;
  size_t atomic_size;

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].density,atomic_size,1,vtk_fp);
  }

}

