/*
  Auto generated by version 0.0 of mat_prop_class_generator.py
  on otsu.local, at 2012-08-25 16:01:49.765841 by dmay
*/


#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "MaterialConst_MaterialType_def.h"


const char MaterialConst_MaterialType_classname[] = "MaterialConst_MaterialType";

const char MaterialConst_MaterialType_classname_short[] = "MaterialType";

const int MaterialConst_MaterialType_nmembers = 4;

const size_t MaterialConst_MaterialType_member_sizes[] = {
  1 * sizeof(int),
  1 * sizeof(int),
  1 * sizeof(int),
  1 * sizeof(int)
} ;

const size_t MaterialConst_MaterialType_member_byte_offset[] = {
  0,
  0 + 1*sizeof(int),
  0 + 1*sizeof(int) + 1*sizeof(int),
  0 + 1*sizeof(int) + 1*sizeof(int) + 1*sizeof(int)
} ;

const char *MaterialConst_MaterialType_member_names_short[] = {
  "visc_type",
  "plastic_type",
  "softening_type",
  "density_type"
} ;

const char *MaterialConst_MaterialType_member_names[] = {
  "visc_type",
  "plastic_type",
  "softening_type",
  "density_type"
} ;


/* ===================================== */
/* Getters for MaterialConst_MaterialType */
/* ===================================== */
void MaterialConst_MaterialTypeGetField_visc_type(MaterialConst_MaterialType *point,int *data) 
{
  *data = point->visc_type;
}

void MaterialConst_MaterialTypeGetField_plastic_type(MaterialConst_MaterialType *point,int *data) 
{
  *data = point->plastic_type;
}

void MaterialConst_MaterialTypeGetField_softening_type(MaterialConst_MaterialType *point,int *data) 
{
  *data = point->softening_type;
}

void MaterialConst_MaterialTypeGetField_density_type(MaterialConst_MaterialType *point,int *data) 
{
  *data = point->density_type;
}


/* ===================================== */
/* Setters for MaterialConst_MaterialType */
/* ===================================== */
void MaterialConst_MaterialTypeSetField_visc_type(MaterialConst_MaterialType *point,int data) 
{
  point->visc_type = data;
}

void MaterialConst_MaterialTypeSetField_plastic_type(MaterialConst_MaterialType *point,int data) 
{
  point->plastic_type = data;
}

void MaterialConst_MaterialTypeSetField_softening_type(MaterialConst_MaterialType *point,int data) 
{
  point->softening_type = data;
}

void MaterialConst_MaterialTypeSetField_density_type(MaterialConst_MaterialType *point,int data) 
{
  point->density_type = data;
}


/* ===================================== */
/* C-viewer for MaterialConst_MaterialType */
/* ===================================== */
void MaterialConst_MaterialTypeView(MaterialConst_MaterialType *point)
{
  {
    int data;
    MaterialConst_MaterialTypeGetField_visc_type(point,&data);
    printf("field: visc_type = %d; [size %zu; type int; variable_name visc_type]\n",data, MaterialConst_MaterialType_member_sizes[0] );
  }
  {
    int data;
    MaterialConst_MaterialTypeGetField_plastic_type(point,&data);
    printf("field: plastic_type = %d; [size %zu; type int; variable_name plastic_type]\n",data, MaterialConst_MaterialType_member_sizes[1] );
  }
  {
    int data;
    MaterialConst_MaterialTypeGetField_softening_type(point,&data);
    printf("field: softening_type = %d; [size %zu; type int; variable_name softening_type]\n",data, MaterialConst_MaterialType_member_sizes[2] );
  }
  {
    int data;
    MaterialConst_MaterialTypeGetField_density_type(point,&data);
    printf("field: density_type = %d; [size %zu; type int; variable_name density_type]\n",data, MaterialConst_MaterialType_member_sizes[3] );
  }
}

