/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on otsu.local, at 2013-01-28 10:38:57.347324 by dmay
*/


#ifndef __MaterialConst_MaterialType_DEF_H__
#define __MaterialConst_MaterialType_DEF_H__

typedef struct {
  int visc_type ;
  int plastic_type ;
  int softening_type ;
  int density_type ;
} MaterialConst_MaterialType ;


typedef enum {
  MaterialType_visc_type = 0,
  MaterialType_plastic_type,
  MaterialType_softening_type,
  MaterialType_density_type
} MaterialConst_MaterialTypeTypeName ;


extern const char MaterialConst_MaterialType_classname[];

extern const int MaterialConst_MaterialType_nmembers;

extern const size_t MaterialConst_MaterialType_member_sizes[];

extern const char *MaterialConst_MaterialType_member_names[];

/* prototypes */
void MaterialConst_MaterialTypeGetField_visc_type(MaterialConst_MaterialType *point,int *data);
void MaterialConst_MaterialTypeGetField_plastic_type(MaterialConst_MaterialType *point,int *data);
void MaterialConst_MaterialTypeGetField_softening_type(MaterialConst_MaterialType *point,int *data);
void MaterialConst_MaterialTypeGetField_density_type(MaterialConst_MaterialType *point,int *data);
void MaterialConst_MaterialTypeSetField_visc_type(MaterialConst_MaterialType *point,int data);
void MaterialConst_MaterialTypeSetField_plastic_type(MaterialConst_MaterialType *point,int data);
void MaterialConst_MaterialTypeSetField_softening_type(MaterialConst_MaterialType *point,int data);
void MaterialConst_MaterialTypeSetField_density_type(MaterialConst_MaterialType *point,int data);
void MaterialConst_MaterialTypeView(MaterialConst_MaterialType *point);
void MaterialConst_MaterialTypeVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_MaterialType points[]);
void MaterialConst_MaterialTypePVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_MaterialTypeVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_MaterialType points[]);
void MaterialConst_MaterialTypeVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_MaterialType points[]);

#endif
