/*@ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 **
 **    Copyright (c) 2012
 **        Dave A. May [dave.may@erdw.ethz.ch]
 **        Institute of Geophysics
 **        ETH Zürich
 **        Sonneggstrasse 5
 **        CH-8092 Zürich
 **        Switzerland
 **
 **    project:    pTatin3d
 **    filename:   MaterialConst_DensityBoussinesq_def.h
 **
 **
 **    pTatin3d is free software: you can redistribute it and/or modify
 **    it under the terms of the GNU General Public License as published
 **    by the Free Software Foundation, either version 3 of the License,
 **    or (at your option) any later version.
 **
 **    pTatin3d is distributed in the hope that it will be useful,
 **    but WITHOUT ANY WARRANTY; without even the implied warranty of
 **    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 **    See the GNU General Public License for more details.
 **
 **    You should have received a copy of the GNU General Public License
 **    along with pTatin3d. If not, see <http://www.gnu.org/licenses/>.
 **
 ** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ @*/



/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on les-MacBook-Pro.local, at 2013-03-08 17:43:59.345347 by laetitia
*/


#ifndef __MaterialConst_DensityBoussinesq_DEF_H__
#define __MaterialConst_DensityBoussinesq_DEF_H__

typedef struct {
  double density ;
  double alpha ;
  double beta ;
} MaterialConst_DensityBoussinesq ;


typedef enum {
  DensityBoussinesq_density = 0,
  DensityBoussinesq_thermalexpension,
  DensityBoussinesq_compressibility
} MaterialConst_DensityBoussinesqTypeName ;


extern const char MaterialConst_DensityBoussinesq_classname[];

extern const int MaterialConst_DensityBoussinesq_nmembers;

extern const size_t MaterialConst_DensityBoussinesq_member_sizes[];

extern const char *MaterialConst_DensityBoussinesq_member_names[];

/* prototypes */
void MaterialConst_DensityBoussinesqGetField_density(MaterialConst_DensityBoussinesq *point,double *data);
void MaterialConst_DensityBoussinesqGetField_thermalexpension(MaterialConst_DensityBoussinesq *point,double *data);
void MaterialConst_DensityBoussinesqGetField_compressibility(MaterialConst_DensityBoussinesq *point,double *data);
void MaterialConst_DensityBoussinesqSetField_density(MaterialConst_DensityBoussinesq *point,double data);
void MaterialConst_DensityBoussinesqSetField_thermalexpension(MaterialConst_DensityBoussinesq *point,double data);
void MaterialConst_DensityBoussinesqSetField_compressibility(MaterialConst_DensityBoussinesq *point,double data);
void MaterialConst_DensityBoussinesqView(MaterialConst_DensityBoussinesq *point);
void MaterialConst_DensityBoussinesqVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityBoussinesq points[]);
void MaterialConst_DensityBoussinesqPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_DensityBoussinesqVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_DensityBoussinesq points[]);
void MaterialConst_DensityBoussinesqVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityBoussinesq points[]);

#endif
