/*@ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 **
 **    Copyright (c) 2012
 **        Dave A. May [dave.may@erdw.ethz.ch]
 **        Institute of Geophysics
 **        ETH Zürich
 **        Sonneggstrasse 5
 **        CH-8092 Zürich
 **        Switzerland
 **
 **    project:    pTatin3d
 **    filename:   MaterialConst_SoftLin_def.h
 **
 **
 **    pTatin3d is free software: you can redistribute it and/or modify
 **    it under the terms of the GNU General Public License as published
 **    by the Free Software Foundation, either version 3 of the License,
 **    or (at your option) any later version.
 **
 **    pTatin3d is distributed in the hope that it will be useful,
 **    but WITHOUT ANY WARRANTY; without even the implied warranty of
 **    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 **    See the GNU General Public License for more details.
 **
 **    You should have received a copy of the GNU General Public License
 **    along with pTatin3d. If not, see <http://www.gnu.org/licenses/>.
 **
 ** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ @*/
/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on les-MacBook-Pro.local, at 2013-03-08 17:43:59.346854 by laetitia
*/


#ifndef __MaterialConst_SoftLin_DEF_H__
#define __MaterialConst_SoftLin_DEF_H__

typedef struct {
  double eps_min ;
  double eps_max ;
} MaterialConst_SoftLin ;


typedef enum {
  SoftLin_eps_min = 0,
  SoftLin_eps_max
} MaterialConst_SoftLinTypeName ;


extern const char MaterialConst_SoftLin_classname[];

extern const int MaterialConst_SoftLin_nmembers;

extern const size_t MaterialConst_SoftLin_member_sizes[];

extern const char *MaterialConst_SoftLin_member_names[];

/* prototypes */
void MaterialConst_SoftLinGetField_eps_min(MaterialConst_SoftLin *point,double *data);
void MaterialConst_SoftLinGetField_eps_max(MaterialConst_SoftLin *point,double *data);
void MaterialConst_SoftLinSetField_eps_min(MaterialConst_SoftLin *point,double data);
void MaterialConst_SoftLinSetField_eps_max(MaterialConst_SoftLin *point,double data);
void MaterialConst_SoftLinView(MaterialConst_SoftLin *point);
void MaterialConst_SoftLinVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_SoftLin points[]);
void MaterialConst_SoftLinPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_SoftLinVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_SoftLin points[]);
void MaterialConst_SoftLinVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_SoftLin points[]);

#endif
