


/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on les-MacBook-Pro.local, at 2013-03-08 17:43:59.345347 by laetitia
*/


#ifndef __MaterialConst_DensityBoussinesq_DEF_H__
#define __MaterialConst_DensityBoussinesq_DEF_H__

typedef struct {
  double density ;
  double alpha ;
  double beta ;
} MaterialConst_DensityBoussinesq ;


typedef enum {
  DensityBoussinesq_density = 0,
  DensityBoussinesq_thermalexpension,
  DensityBoussinesq_compressibility
} MaterialConst_DensityBoussinesqTypeName ;


extern const char MaterialConst_DensityBoussinesq_classname[];

extern const int MaterialConst_DensityBoussinesq_nmembers;

extern const size_t MaterialConst_DensityBoussinesq_member_sizes[];

extern const char *MaterialConst_DensityBoussinesq_member_names[];

/* prototypes */
void MaterialConst_DensityBoussinesqGetField_density(MaterialConst_DensityBoussinesq *point,double *data);
void MaterialConst_DensityBoussinesqGetField_thermalexpension(MaterialConst_DensityBoussinesq *point,double *data);
void MaterialConst_DensityBoussinesqGetField_compressibility(MaterialConst_DensityBoussinesq *point,double *data);
void MaterialConst_DensityBoussinesqSetField_density(MaterialConst_DensityBoussinesq *point,double data);
void MaterialConst_DensityBoussinesqSetField_thermalexpension(MaterialConst_DensityBoussinesq *point,double data);
void MaterialConst_DensityBoussinesqSetField_compressibility(MaterialConst_DensityBoussinesq *point,double data);
void MaterialConst_DensityBoussinesqView(MaterialConst_DensityBoussinesq *point);
void MaterialConst_DensityBoussinesqVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityBoussinesq points[]);
void MaterialConst_DensityBoussinesqPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_DensityBoussinesqVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_DensityBoussinesq points[]);
void MaterialConst_DensityBoussinesqVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityBoussinesq points[]);

#endif
