/*
  Auto generated by version 0.0 of mat_prop_class_generator.py
  on otsu.local, at 2012-08-25 16:01:49.766091 by dmay
*/


#ifndef __MaterialConst_ViscosityConst_DEF_H__
#define __MaterialConst_ViscosityConst_DEF_H__

typedef struct {
  double eta0 ;
} MaterialConst_ViscosityConst ;


typedef enum {
  ViscConst_eta0 = 0
} MaterialConst_ViscosityConstTypeName ;


extern const char MaterialConst_ViscosityConst_classname[];

extern const char MaterialConst_ViscosityConst_classname_short[];

extern const int MaterialConst_ViscosityConst_nmembers;

extern const size_t MaterialConst_ViscosityConst_member_sizes[];

extern const char *MaterialConst_ViscosityConst_member_names_short[];

extern const char *MaterialConst_ViscosityConst_member_names[];

extern const size_t MaterialConst_ViscosityConst_member_byte_offset[];

/* prototypes */
void MaterialConst_ViscosityConstGetField_eta0(MaterialConst_ViscosityConst *point,double *data);
void MaterialConst_ViscosityConstSetField_eta0(MaterialConst_ViscosityConst *point,double data);
void MaterialConst_ViscosityConstView(MaterialConst_ViscosityConst *point);

#endif
