/*
  Auto generated by version 0.0 of mat_prop_class_generator.py
  on otsu.local, at 2012-08-25 16:01:49.765582 by dmay
*/


#ifndef __MaterialConst_MaterialType_DEF_H__
#define __MaterialConst_MaterialType_DEF_H__

typedef struct {
  int visc_type ;
  int plastic_type ;
  int softening_type ;
  int density_type ;
} MaterialConst_MaterialType ;


typedef enum {
  MaterialType_visc_type = 0,
  MaterialType_plastic_type,
  MaterialType_softening_type,
  MaterialType_density_type
} MaterialConst_MaterialTypeTypeName ;


extern const char MaterialConst_MaterialType_classname[];

extern const char MaterialConst_MaterialType_classname_short[];

extern const int MaterialConst_MaterialType_nmembers;

extern const size_t MaterialConst_MaterialType_member_sizes[];

extern const char *MaterialConst_MaterialType_member_names_short[];

extern const char *MaterialConst_MaterialType_member_names[];

extern const size_t MaterialConst_MaterialType_member_byte_offset[];

/* prototypes */
void MaterialConst_MaterialTypeGetField_visc_type(MaterialConst_MaterialType *point,int *data);
void MaterialConst_MaterialTypeGetField_plastic_type(MaterialConst_MaterialType *point,int *data);
void MaterialConst_MaterialTypeGetField_softening_type(MaterialConst_MaterialType *point,int *data);
void MaterialConst_MaterialTypeGetField_density_type(MaterialConst_MaterialType *point,int *data);
void MaterialConst_MaterialTypeSetField_visc_type(MaterialConst_MaterialType *point,int data);
void MaterialConst_MaterialTypeSetField_plastic_type(MaterialConst_MaterialType *point,int data);
void MaterialConst_MaterialTypeSetField_softening_type(MaterialConst_MaterialType *point,int data);
void MaterialConst_MaterialTypeSetField_density_type(MaterialConst_MaterialType *point,int data);
void MaterialConst_MaterialTypeView(MaterialConst_MaterialType *point);

#endif
