/*
  Auto generated by version 0.0 of mat_prop_class_generator.py
  on otsu.local, at 2012-08-25 16:01:49.766231 by dmay
*/


#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "MaterialConst_ViscosityConst_def.h"


const char MaterialConst_ViscosityConst_classname[] = "MaterialConst_ViscosityConst";

const char MaterialConst_ViscosityConst_classname_short[] = "ViscConst";

const int MaterialConst_ViscosityConst_nmembers = 1;

const size_t MaterialConst_ViscosityConst_member_sizes[] = {
  1 * sizeof(double)
} ;

const size_t MaterialConst_ViscosityConst_member_byte_offset[] = {
  0
} ;

const char *MaterialConst_ViscosityConst_member_names_short[] = {
  "eta0"
} ;

const char *MaterialConst_ViscosityConst_member_names[] = {
  "eta0"
} ;


/* ===================================== */
/* Getters for MaterialConst_ViscosityConst */
/* ===================================== */
void MaterialConst_ViscosityConstGetField_eta0(MaterialConst_ViscosityConst *point,double *data) 
{
  *data = point->eta0;
}


/* ===================================== */
/* Setters for MaterialConst_ViscosityConst */
/* ===================================== */
void MaterialConst_ViscosityConstSetField_eta0(MaterialConst_ViscosityConst *point,double data) 
{
  point->eta0 = data;
}


/* ===================================== */
/* C-viewer for MaterialConst_ViscosityConst */
/* ===================================== */
void MaterialConst_ViscosityConstView(MaterialConst_ViscosityConst *point)
{
  {
    double data;
    MaterialConst_ViscosityConstGetField_eta0(point,&data);
    printf("field: eta0 = %1.6e; [size %zu; type double; variable_name eta0]\n",data, MaterialConst_ViscosityConst_member_sizes[0] );
  }
}

