/*@ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 **
 **    Copyright (c) 2012
 **        Dave A. May [dave.may@erdw.ethz.ch]
 **        Institute of Geophysics
 **        ETH Zürich
 **        Sonneggstrasse 5
 **        CH-8092 Zürich
 **        Switzerland
 **
 **    project:    pTatin3d
 **    filename:   MPntPStokes_def.h
 **
 **
 **    pTatin3d is free software: you can redistribute it and/or modify
 **    it under the terms of the GNU General Public License as published
 **    by the Free Software Foundation, either version 3 of the License,
 **    or (at your option) any later version.
 **
 **    pTatin3d is distributed in the hope that it will be useful,
 **    but WITHOUT ANY WARRANTY; without even the implied warranty of
 **    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 **    See the GNU General Public License for more details.
 **
 **    You should have received a copy of the GNU General Public License
 **    along with pTatin3d. If not, see <http://www.gnu.org/licenses/>.
 **
 ** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ @*/



/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on otsu.local, at 2012-02-13 00:08:18.106542 by dmay
*/


#ifndef __MPntPStokes_DEF_H__
#define __MPntPStokes_DEF_H__

typedef struct {
  double eta ;
  double rho ;
} MPntPStokes ;


typedef enum {
  MPPStk_eta_effective = 0,
  MPPStk_density
} MPntPStokesTypeName ;


extern const char MPntPStokes_classname[];

extern const int MPntPStokes_nmembers;

extern const size_t MPntPStokes_member_sizes[];

extern const char *MPntPStokes_member_names[];

/* prototypes */
void MPntPStokesGetField_eta_effective(MPntPStokes *point,double *data);
void MPntPStokesGetField_density(MPntPStokes *point,double *data);
void MPntPStokesSetField_eta_effective(MPntPStokes *point,double data);
void MPntPStokesSetField_density(MPntPStokes *point,double data);
void MPntPStokesView(MPntPStokes *point);
void MPntPStokesVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MPntPStokes points[]);
void MPntPStokesPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MPntPStokesVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MPntPStokes points[]);
void MPntPStokesVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MPntPStokes points[]);

#endif
