/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on DESKTOP-4R168SI, at 2018-09-06 14:33:48.294992 by tony
*/

#ifndef __MPntPStokes_DEF_H__
#define __MPntPStokes_DEF_H__

#include <mpi.h>

typedef struct {
 double eta;
 double rho;
 float e_viscous;
} MPntPStokes;

typedef enum {
  MPPStk_eta_effective = 0,
  MPPStk_density,
  MPPStk_viscous_strain
} MPntPStokesTypeName;

extern const char MPntPStokes_classname[];

extern const int MPntPStokes_nmembers;

extern const size_t MPntPStokes_member_sizes[];

extern const char *MPntPStokes_member_names[];

extern MPI_Datatype MPI_MPNTPSTOKES;

/* prototypes */
void MPntPStokesGetField_eta_effective(MPntPStokes *point,double *data);
void MPntPStokesGetField_density(MPntPStokes *point,double *data);
void MPntPStokesGetField_viscous_strain(MPntPStokes *point,float *data);
void MPntPStokesSetField_eta_effective(MPntPStokes *point,double data);
void MPntPStokesSetField_density(MPntPStokes *point,double data);
void MPntPStokesSetField_viscous_strain(MPntPStokes *point,float data);
void MPntPStokesView(MPntPStokes *point);
void MPntPStokesVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MPntPStokes points[]);
void MPntPStokesPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MPntPStokesVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MPntPStokes points[]);
void MPntPStokesVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MPntPStokes points[]);
int MPntPStokesCreateMPIDataType(MPI_Datatype *ptype);

#endif
