libptatin3dmodels-y.c += $(call thisdir, \
			ptatin_models_reg.c \
			folding/model_folding_ops.c \
			folding2d/model_ops_folding2d.c \
			gene3d/model_ops_gene3d.c \
			gene3d_nueve/model_ops_gene3d_nueve.c \
			indentor/model_indentor_ops.c \
			rift3D/model_rift3D_ops.c \
			sierra/model_ops_Sierra.c \
			template/model_ops_template.c \
			viscous_sinker/model_viscous_sinker_ops.c \
			advdiff_example/model_ops_advdiff_example.c \
			basin_comp/model_ops_basin_comp.c \
			delamination/model_delamination_ops.c \
			ex_subduction/ex_subduction_ops.c \
			fault_fold/model_ops_fault_fold.c \
			fault_fold_plastic/model_ops_fault_fold_plastic.c \
			geomod2008/model_geomod2008.c \
			iplus_slab_plume/iplus_ops.c \
			iplus_slab_plume/iplus_plume_description.c \
			iplus_slab_plume/iplus_slab_description.c \
			multilayer_folding/compute_analytic_growth_rate_3d.c \
			multilayer_folding/model_ops_multilayer_folding.c \
			rift3D_T/model_rift3D_T_ops.c \
			riftrh/model_ops_riftrh.c \
			submarinelavaflow/profiles/plot_profiles.c \
			submarinelavaflow/submarinelavaflow_ops.c \
			wrench_fold/model_ops_wrench_fold.c \
			convection2d/model_convection2d_ops.c \
			subduction_initiation2d/model_subduction_initiation2d_ops.c \
			plasticdemo/demo.c \
	)
