
/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on geop-265.ethz.ch, at 2015-08-25 11:20:15.233463 by dmay
*/

#ifndef __MPntPEVSS_DEF_H__
#define __MPntPEVSS_DEF_H__

#include <mpi.h>

typedef struct {
 double tau[6];
 double mu;
 double eta_e;
} MPntPEVSS;

typedef enum {
  MPPEVSS_deviatoric_stress = 0,
  MPPEVSS_shear_modulus,
  MPPEVSS_solid_viscosity
} MPntPEVSSTypeName;

extern const char MPntPEVSS_classname[];

extern const int MPntPEVSS_nmembers;

extern const size_t MPntPEVSS_member_sizes[];

extern const char *MPntPEVSS_member_names[];

extern MPI_Datatype MPI_MPNTPEVSS;

/* prototypes */
void MPntPEVSSGetField_deviatoric_stress(MPntPEVSS *point,double *data[]);
void MPntPEVSSGetField_shear_modulus(MPntPEVSS *point,double *data);
void MPntPEVSSGetField_solid_viscosity(MPntPEVSS *point,double *data);
void MPntPEVSSSetField_deviatoric_stress(MPntPEVSS *point,double data[]);
void MPntPEVSSSetField_shear_modulus(MPntPEVSS *point,double data);
void MPntPEVSSSetField_solid_viscosity(MPntPEVSS *point,double data);
void MPntPEVSSView(MPntPEVSS *point);
void MPntPEVSSVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MPntPEVSS points[]);
void MPntPEVSSPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MPntPEVSSVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MPntPEVSS points[]);
void MPntPEVSSVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MPntPEVSS points[]);
int MPntPEVSSCreateMPIDataType(MPI_Datatype *ptype);

#endif
