
/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on geop-265.ethz.ch, at 2015-08-26 09:51:16.428496 by dmay
*/

#include <stdio.h>
#include <string.h>
#include <mpi.h>

#include "QPntVolCoefSymTens_def.h"


const char QPntVolCoefSymTens_classname[] = "QPntVolCoefSymTens";

const int QPntVolCoefSymTens_nmembers = 1;

const size_t QPntVolCoefSymTens_member_sizes[] = {
  6 * sizeof(double)
};

const char *QPntVolCoefSymTens_member_names[] = {
  "symmetric_tensir"
};

MPI_Datatype MPI_QPNTVOLCOEFSYMTENS;


/* ===================================== */
/* Getters for QPntVolCoefSymTens */
/* ===================================== */
void QPntVolCoefSymTensGetField_symmetric_tensir(QPntVolCoefSymTens *point,double *data[]) 
{
  *data = point->T;
}


/* ===================================== */
/* Setters for QPntVolCoefSymTens */
/* ===================================== */
void QPntVolCoefSymTensSetField_symmetric_tensir(QPntVolCoefSymTens *point,double data[]) 
{
  memcpy( &point->T[0], data, sizeof(double)*6 );
}


/* ===================================== */
/* C-viewer for QPntVolCoefSymTens */
/* ===================================== */
void QPntVolCoefSymTensView(QPntVolCoefSymTens *point)
{
  {
    double *data;
    QPntVolCoefSymTensGetField_symmetric_tensir(point,&data);
    printf("field: symmetric_tensir[0] = %1.6e; [size %zu; type double; variable_name T]\n",data[0], QPntVolCoefSymTens_member_sizes[0] );
    printf("field: symmetric_tensir[1] = %1.6e; [size %zu; type double; variable_name T]\n",data[1], QPntVolCoefSymTens_member_sizes[0] );
    printf("field: symmetric_tensir[2] = %1.6e; [size %zu; type double; variable_name T]\n",data[2], QPntVolCoefSymTens_member_sizes[0] );
    printf("field: symmetric_tensir[3] = %1.6e; [size %zu; type double; variable_name T]\n",data[3], QPntVolCoefSymTens_member_sizes[0] );
    printf("field: symmetric_tensir[4] = %1.6e; [size %zu; type double; variable_name T]\n",data[4], QPntVolCoefSymTens_member_sizes[0] );
    printf("field: symmetric_tensir[5] = %1.6e; [size %zu; type double; variable_name T]\n",data[5], QPntVolCoefSymTens_member_sizes[0] );
  }
}


/* ===================================== */
/* VTK viewer for QPntVolCoefSymTens */
/* ===================================== */
void QPntVolCoefSymTensVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const QPntVolCoefSymTens points[]) 
{
  int p;
}


/* ===================================== */
/* PVTU viewer for QPntVolCoefSymTens */
/* ===================================== */
void QPntVolCoefSymTensPVTUWriteAllPPointDataFields(FILE *vtk_fp) 
{
}


/* ===================================== */
/* VTK binary (appended header) viewer for QPntVolCoefSymTens */
/* ===================================== */
void QPntVolCoefSymTensVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const QPntVolCoefSymTens points[]) 
{
  /* Warning: swarm_class_generator.py is ignoring multi-component field T[] */

}


/* ================================================== */
/* VTK binary (appended data) viewer for QPntVolCoefSymTens */
/* ==================================================== */
void QPntVolCoefSymTensVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const QPntVolCoefSymTens points[]) 
{
  int p,length;
  size_t atomic_size;

  /* Warning: swarm_class_generator.py is ignoring multi-component field T[] */

}


/* ===================================== */
/* MPI data type for QPntVolCoefSymTens */
/* ===================================== */
int QPntVolCoefSymTensCreateMPIDataType(MPI_Datatype *ptype)
{
  MPI_Datatype newtype;
  MPI_Datatype types[] = { MPI_DOUBLE };
  int blocklens[] = { 6 };
  MPI_Aint loc[2];
  MPI_Aint disp[1];
  QPntVolCoefSymTens dummy;
  int i,ierr;

  ierr = MPI_Get_address(&dummy,&loc[0]);
  ierr = MPI_Get_address(&dummy.T,&loc[1]);

  for (i=0; i<1; i++) {
    disp[i] = loc[i+1] - loc[0];
  }

  ierr = MPI_Type_create_struct(1,blocklens,disp,types,&newtype);
  ierr = MPI_Type_commit(&newtype);
  *ptype = newtype;
  return 0;
}

