/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on otsu.local, at 2013-02-02 20:59:58.571350 by dmay
*/


#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "QPntVolCoefEnergy_def.h"


const char QPntVolCoefEnergy_classname[] = "QPntVolCoefEnergy";

const int QPntVolCoefEnergy_nmembers = 2;

const size_t QPntVolCoefEnergy_member_sizes[] = {
  1 * sizeof(double),
  1 * sizeof(double)
} ;

const char *QPntVolCoefEnergy_member_names[] = {
  "diffusivity",
  "heat_source"
} ;


/* ===================================== */
/* Getters for QPntVolCoefEnergy */
/* ===================================== */
void QPntVolCoefEnergyGetField_diffusivity(QPntVolCoefEnergy *point,double *data) 
{
  *data = point->diffusivity;
}

void QPntVolCoefEnergyGetField_heat_source(QPntVolCoefEnergy *point,double *data) 
{
  *data = point->heat_source;
}


/* ===================================== */
/* Setters for QPntVolCoefEnergy */
/* ===================================== */
void QPntVolCoefEnergySetField_diffusivity(QPntVolCoefEnergy *point,double data) 
{
  point->diffusivity = data;
}

void QPntVolCoefEnergySetField_heat_source(QPntVolCoefEnergy *point,double data) 
{
  point->heat_source = data;
}


/* ===================================== */
/* C-viewer for QPntVolCoefEnergy */
/* ===================================== */
void QPntVolCoefEnergyView(QPntVolCoefEnergy *point)
{
  {
    double data;
    QPntVolCoefEnergyGetField_diffusivity(point,&data);
    printf("field: diffusivity = %1.6e; [size %zu; type double; variable_name diffusivity]\n",data, QPntVolCoefEnergy_member_sizes[0] );
  }
  {
    double data;
    QPntVolCoefEnergyGetField_heat_source(point,&data);
    printf("field: heat_source = %1.6e; [size %zu; type double; variable_name heat_source]\n",data, QPntVolCoefEnergy_member_sizes[1] );
  }
}


/* ===================================== */
/* VTK viewer for QPntVolCoefEnergy */
/* ===================================== */
void QPntVolCoefEnergyVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const QPntVolCoefEnergy points[]) 
{
  int p;
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"diffusivity\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].diffusivity);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"heat_source\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].heat_source);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
}


/* ===================================== */
/* PVTU viewer for QPntVolCoefEnergy */
/* ===================================== */
void QPntVolCoefEnergyPVTUWriteAllPPointDataFields(FILE *vtk_fp) 
{
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"diffusivity\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"heat_source\" NumberOfComponents=\"1\"/>\n");
}


/* ===================================== */
/* VTK binary (appended header) viewer for QPntVolCoefEnergy */
/* ===================================== */
void QPntVolCoefEnergyVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const QPntVolCoefEnergy points[]) 
{
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"diffusivity\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"heat_source\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

}


/* ================================================== */
/* VTK binary (appended data) viewer for QPntVolCoefEnergy */
/* ==================================================== */
void QPntVolCoefEnergyVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const QPntVolCoefEnergy points[]) 
{
  int p,length;
  size_t atomic_size;

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].diffusivity,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].heat_source,atomic_size,1,vtk_fp);
  }

}

